
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResCustomer
{

    public ResCustomer()
    {

        this.ResOrderHds = new HashSet<ResOrderHd>();

    }


    public decimal CustId { get; set; }

    public string CustNameA { get; set; }

    public string CustNameE { get; set; }

    public string CustAddressA { get; set; }

    public string CustAddressE { get; set; }

    public Nullable<decimal> GovId { get; set; }

    public Nullable<decimal> AreaId { get; set; }

    public string Street { get; set; }

    public Nullable<int> BuildingNo { get; set; }

    public Nullable<int> ApartmentNo { get; set; }

    public string Tel1 { get; set; }

    public string Tel2 { get; set; }

    public string Tel3 { get; set; }

    public string Comment { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }

    public Nullable<decimal> CustType { get; set; }



    public virtual ResAreaCode ResAreaCode { get; set; }

    public virtual ResCustomerType ResCustomerType { get; set; }

    public virtual ICollection<ResOrderHd> ResOrderHds { get; set; }

}

}
