
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResItemCode
{

    public ResItemCode()
    {

        this.ResOrderDtls = new HashSet<ResOrderDtl>();

    }


    public decimal ItemId { get; set; }

    public decimal MainCategoryId { get; set; }

    public decimal SubCategoryId { get; set; }

    public Nullable<decimal> PropertyId { get; set; }

    public Nullable<decimal> Property2Id { get; set; }

    public Nullable<decimal> MenuSalesId { get; set; }

    public Nullable<decimal> CostPrice { get; set; }

    public Nullable<decimal> SalesPrice { get; set; }

    public Nullable<decimal> OpenQty { get; set; }

    public Nullable<decimal> CurrentQty { get; set; }

    public string Comment { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ResMenuSalesCode ResMenuSalesCode { get; set; }

    public virtual ResProperty2Codes ResProperty2Codes { get; set; }

    public virtual ResPropertyCode ResPropertyCode { get; set; }

    public virtual ICollection<ResOrderDtl> ResOrderDtls { get; set; }

    public virtual ResSubCategoryCode ResSubCategoryCode { get; set; }

}

}
