
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResJOBCode
{

    public ResJOBCode()
    {

        this.ResEmployeeBasics = new HashSet<ResEmployeeBasic>();

    }


    public decimal JobId { get; set; }

    public string JobNameA { get; set; }

    public string JobNameE { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ICollection<ResEmployeeBasic> ResEmployeeBasics { get; set; }

}

}
