
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResMainCategoryCode
{

    public ResMainCategoryCode()
    {

        this.ResSubCategoryCodes = new HashSet<ResSubCategoryCode>();

    }


    public decimal MainCategoryId { get; set; }

    public string MainCategoryNameA { get; set; }

    public string MainCategoryNameE { get; set; }

    public Nullable<decimal> PrintGroupNo { get; set; }

    public Nullable<decimal> ShowInInvoice { get; set; }

    public Nullable<decimal> TypeId { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }

    public Nullable<decimal> CountableStatus { get; set; }

    public byte[] MainImage { get; set; }



    public virtual ResItemType ResItemType { get; set; }

    public virtual ICollection<ResSubCategoryCode> ResSubCategoryCodes { get; set; }

}

}
