
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResMenuSalesCode
{

    public ResMenuSalesCode()
    {

        this.ResItemCodes = new HashSet<ResItemCode>();

    }


    public decimal MenuSalesId { get; set; }

    public string MenuSalesNameA { get; set; }

    public string MenuSalesNameE { get; set; }

    public Nullable<decimal> seq { get; set; }



    public virtual ICollection<ResItemCode> ResItemCodes { get; set; }

}

}
