
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResOrderHd
{

    public ResOrderHd()
    {

        this.ResOrderDtls = new HashSet<ResOrderDtl>();

        this.ResPayments = new HashSet<ResPayment>();

    }


    public decimal OrederId { get; set; }

    public decimal BranchId { get; set; }

    public decimal OrderNo { get; set; }

    public System.DateTime OrderDt { get; set; }

    public Nullable<decimal> OrderType { get; set; }

    public Nullable<System.DateTime> OrderTime { get; set; }

    public decimal ShiftId { get; set; }

    public decimal CustId { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public Nullable<decimal> PriceAdd { get; set; }

    public Nullable<decimal> DiscountRatio { get; set; }

    public Nullable<decimal> DiscountVal { get; set; }

    public Nullable<decimal> ServiceVal { get; set; }

    public Nullable<decimal> NetPrice { get; set; }

    public Nullable<decimal> CashVal { get; set; }

    public Nullable<decimal> RemainderVal { get; set; }

    public Nullable<decimal> SwDelete { get; set; }

    public Nullable<decimal> OrderStatus { get; set; }

    public Nullable<decimal> DeliveryId { get; set; }

    public Nullable<decimal> DeliveryStatus { get; set; }

    public Nullable<System.DateTime> ToDeliveryTime { get; set; }

    public Nullable<System.DateTime> DeliveryTimeRequired { get; set; }

    public Nullable<System.DateTime> FromDeliveryTime { get; set; }

    public Nullable<int> TableNo { get; set; }

    public Nullable<int> PeopleCount { get; set; }

    public string UserName { get; set; }

    public string UserNameDeleted { get; set; }

    public string Comment { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ResCustomer ResCustomer { get; set; }

    public virtual ResDeliveryStatu ResDeliveryStatu { get; set; }

    public virtual ResEmployeeBasic ResEmployeeBasic { get; set; }

    public virtual ICollection<ResOrderDtl> ResOrderDtls { get; set; }

    public virtual ICollection<ResPayment> ResPayments { get; set; }

    public virtual ResOrderStatu ResOrderStatu { get; set; }

    public virtual ResOrderType ResOrderType { get; set; }

    public virtual ResShiftsCode ResShiftsCode { get; set; }

    public virtual ResStoresCode ResStoresCode { get; set; }

    public virtual ResTablesCode ResTablesCode { get; set; }

}

}
