
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResOrderDtl
{

    public ResOrderDtl()
    {

        this.ResInstructionCodes = new HashSet<ResInstructionCode>();

    }


    public decimal OrederId { get; set; }

    public decimal SeqNo { get; set; }

    public decimal ItemId { get; set; }

    public Nullable<decimal> Qty { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> CookStatus { get; set; }

    public Nullable<System.DateTime> CookStatusTime { get; set; }



    public virtual ResCookStatusCode ResCookStatusCode { get; set; }

    public virtual ResItemCode ResItemCode { get; set; }

    public virtual ResOrderHd ResOrderHd { get; set; }

    public virtual ICollection<ResInstructionCode> ResInstructionCodes { get; set; }

}

}
