
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResPropertyCode
{

    public ResPropertyCode()
    {

        this.ResItemCodes = new HashSet<ResItemCode>();

    }


    public decimal PropertyId { get; set; }

    public string PropertyNameA { get; set; }

    public string PropertyNameE { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ICollection<ResItemCode> ResItemCodes { get; set; }

}

}
