
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResPayment
{

    public decimal DocNo { get; set; }

    public decimal OrederId { get; set; }

    public decimal CashVal { get; set; }

    public Nullable<decimal> CardVal { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ResOrderHd ResOrderHd { get; set; }

}

}
