
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResShiftsCode
{

    public ResShiftsCode()
    {

        this.ResOrderHds = new HashSet<ResOrderHd>();

    }


    public decimal ShiftId { get; set; }

    public string ShiftNameE { get; set; }

    public string ShiftNamea { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }



    public virtual ICollection<ResOrderHd> ResOrderHds { get; set; }

}

}
