
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResStoresCode
{

    public ResStoresCode()
    {

        this.ResOrderHds = new HashSet<ResOrderHd>();

    }


    public decimal BranchId { get; set; }

    public string BranchNameA { get; set; }

    public string BranchNameE { get; set; }

    public decimal GovId { get; set; }

    public string AddressA { get; set; }

    public string AddressE { get; set; }

    public string Tel1 { get; set; }

    public string Tel2 { get; set; }

    public string Tel3 { get; set; }

    public Nullable<decimal> ServiceRatio { get; set; }

    public Nullable<decimal> MinChargeVal { get; set; }

    public Nullable<System.DateTime> StartDt { get; set; }

    public Nullable<decimal> CloseSw { get; set; }

    public Nullable<System.DateTime> CloseDt { get; set; }



    public virtual ResGovCode ResGovCode { get; set; }

    public virtual ICollection<ResOrderHd> ResOrderHds { get; set; }

}

}
