
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResTablesCode
{

    public ResTablesCode()
    {

        this.ResOrderHds = new HashSet<ResOrderHd>();

    }


    public int TableNo { get; set; }

    public string TableName { get; set; }

    public Nullable<decimal> StatusId { get; set; }



    public virtual ICollection<ResOrderHd> ResOrderHds { get; set; }

    public virtual ResTablesStatusCode ResTablesStatusCode { get; set; }

}

}
