
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class ResWorkStatu
{

    public decimal WorkStatus { get; set; }

    public string WorkStatusNameA { get; set; }

    public string WorkStatusNameE { get; set; }

}

}
