
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SecMenue
{

    public int ModuleNo { get; set; }

    public decimal MenuNo { get; set; }

    public string MenuNameA { get; set; }

    public string MenuNameE { get; set; }



    public virtual SecSystem SecSystem { get; set; }

}

}
