
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SecSystem
{

    public SecSystem()
    {

        this.SecForms = new HashSet<SecForm>();

        this.SecMenues = new HashSet<SecMenue>();

    }


    public int ModuleNo { get; set; }

    public string ModuleNameA { get; set; }

    public string ModuleNameE { get; set; }



    public virtual ICollection<SecForm> SecForms { get; set; }

    public virtual ICollection<SecMenue> SecMenues { get; set; }

}

}
