
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Resturant.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SecUser
{

    public SecUser()
    {

        this.SecPermissions = new HashSet<SecPermission>();

    }


    public string UserName { get; set; }

    public string UserPasswd { get; set; }

    public Nullable<decimal> SwSpecialUser { get; set; }

    public Nullable<System.DateTime> InsertDt { get; set; }

    public Nullable<decimal> EmpId { get; set; }



    public virtual ICollection<SecPermission> SecPermissions { get; set; }

}

}
